// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {gitman} from '../models';

export function AutoCheckUpdate():Promise<void>;

export function CheckUpdate():Promise<updater.UpdateStatus>;

export function GetLogs():Promise<string>;

export function GetMirror():Promise<string>;

export function GetVersion():Promise<string>;

export function GitBranches():Promise<Array<gitman.BranchInfo>>;

export function GitCheckout(arg1:string):Promise<void>;

export function GitCreateBranch(arg1:string):Promise<void>;

export function GitHistory(arg1:number):Promise<Array<gitman.CommitDetail>>;

export function GitSwitchBranch(arg1:string):Promise<void>;

export function IsMainProgramRunning():Promise<boolean>;

export function KillMainProgram():Promise<void>;

export function LaunchMainProgram():Promise<void>;

export function LoadConfig():Promise<updater.Config>;

export function Logf(arg1:string,arg2:Array<any>):Promise<void>;

export function PerformUpdate():Promise<void>;

export function Progress(arg1:number):Promise<void>;

export function SetMirror(arg1:string):Promise<void>;
