// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoCheckUpdate() {
  return window['go']['main']['App']['AutoCheckUpdate']();
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetMirror() {
  return window['go']['main']['App']['GetMirror']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GitBranches() {
  return window['go']['main']['App']['GitBranches']();
}

export function GitCheckout(arg1) {
  return window['go']['main']['App']['GitCheckout'](arg1);
}

export function GitCreateBranch(arg1) {
  return window['go']['main']['App']['GitCreateBranch'](arg1);
}

export function GitHistory(arg1) {
  return window['go']['main']['App']['GitHistory'](arg1);
}

export function GitSwitchBranch(arg1) {
  return window['go']['main']['App']['GitSwitchBranch'](arg1);
}

export function IsMainProgramRunning() {
  return window['go']['main']['App']['IsMainProgramRunning']();
}

export function KillMainProgram() {
  return window['go']['main']['App']['KillMainProgram']();
}

export function LaunchMainProgram() {
  return window['go']['main']['App']['LaunchMainProgram']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function Logf(arg1, arg2) {
  return window['go']['main']['App']['Logf'](arg1, arg2);
}

export function PerformUpdate() {
  return window['go']['main']['App']['PerformUpdate']();
}

export function Progress(arg1) {
  return window['go']['main']['App']['Progress'](arg1);
}

export function SetMirror(arg1) {
  return window['go']['main']['App']['SetMirror'](arg1);
}
